In [3]:
import pandas as pd
import numpy as np

In [40]:
infile="jAFS_d3_ParamEst.obs"
obs_sfs = pd.read_table(infile)
obs_sfs

,Unnamed: 0,d0_0,d0_1,d0_2,d0_3,d0_4,d0_5,d0_6,d0_7,d0_8,d0_9,d0_10,d0_11,d0_12,d0_13,d0_14,d0_15,d0_16,d0_17
0,d1_0,3911.403782,1963.986437,816.709673,290.621517,198.815227,110.193343,100.572353,54.142232,44.624047,34.370457,24.884990,19.934954,20.394070,14.861089,52.295976,3075.166872,400.068734,257.628273
1,d1_1,138.488247,96.890736,61.189204,38.318043,27.654157,21.893341,16.879245,14.866526,10.949213,10.380941,10.865531,32.982554,1647.359720,267.443803,208.126466,121.011814,90.710808,64.087487
2,d1_2,42.733594,30.959762,26.179277,22.104910,20.055415,14.157451,14.067305,11.071649,0.000000,802.244593,157.283762,139.679986,90.937660,73.509377,54.383965,40.665374,30.034386,26.297430
3,d1_3,24.769778,18.301261,12.634149,11.711277,0.000000,0.000000,623.679977,114.356632,110.037615,80.616702,72.396587,53.472226,45.198005,37.243576,28.984945,23.382575,20.358830,14.455725
4,d1_4,0.000000,0.000000,0.000000,376.730002,81.102998,82.662571,67.299616,70.090008,50.029625,42.630895,37.031938,29.659269,24.193852,22.325143,0.000000,0.000000,0.000000,0.000000
5,d1_5,267.557115,65.736717,66.278621,58.962031,64.774210,48.979880,45.170745,40.520588,34.696180,27.796298,0.000000,0.000000,0.000000,0.000000,0.000000,184.162929,50.782004,51.075433
6,d1_6,47.258619,50.755050,46.091069,45.475477,41.053068,38.628511,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,138.488064,39.294559,43.538796,41.432706,42.011923,43.188785
7,d1_7,43.198720,41.491416,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,104.167458,31.631605,37.724078,35.671616,34.377144,36.719818,40.117681,0.000000,0.000000
8,d1_8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.960356,26.829745,30.467823,28.356196,29.468957,31.767153,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,d1_9,0.000000,0.000000,0.000000,55.134537,24.279127,26.245930,21.930849,26.729478,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,d1_10,46.157655,19.126968,19.067417,15.811030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.940765,15.088979,16.552107
11,d1_11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.077220,10.225925,0.000000,0.000000,0.000000,0.000000
12,d1_12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.479337,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,d1_13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,d1_14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [41]:
jSFS = obs_sfs.drop(obs_sfs.columns[[0]], axis=1)

In [54]:
jSFS

,d0_0,d0_1,d0_2,d0_3,d0_4,d0_5,d0_6,d0_7,d0_8,d0_9,d0_10,d0_11,d0_12,d0_13,d0_14,d0_15,d0_16,d0_17
0,3911.403782,1963.986437,816.709673,290.621517,198.815227,110.193343,100.572353,54.142232,44.624047,34.370457,24.884990,19.934954,20.394070,14.861089,52.295976,3075.166872,400.068734,257.628273
1,138.488247,96.890736,61.189204,38.318043,27.654157,21.893341,16.879245,14.866526,10.949213,10.380941,10.865531,32.982554,1647.359720,267.443803,208.126466,121.011814,90.710808,64.087487
2,42.733594,30.959762,26.179277,22.104910,20.055415,14.157451,14.067305,11.071649,0.000000,802.244593,157.283762,139.679986,90.937660,73.509377,54.383965,40.665374,30.034386,26.297430
3,24.769778,18.301261,12.634149,11.711277,0.000000,0.000000,623.679977,114.356632,110.037615,80.616702,72.396587,53.472226,45.198005,37.243576,28.984945,23.382575,20.358830,14.455725
4,0.000000,0.000000,0.000000,376.730002,81.102998,82.662571,67.299616,70.090008,50.029625,42.630895,37.031938,29.659269,24.193852,22.325143,0.000000,0.000000,0.000000,0.000000
5,267.557115,65.736717,66.278621,58.962031,64.774210,48.979880,45.170745,40.520588,34.696180,27.796298,0.000000,0.000000,0.000000,0.000000,0.000000,184.162929,50.782004,51.075433
6,47.258619,50.755050,46.091069,45.475477,41.053068,38.628511,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,138.488064,39.294559,43.538796,41.432706,42.011923,43.188785
7,43.198720,41.491416,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,104.167458,31.631605,37.724078,35.671616,34.377144,36.719818,40.117681,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.960356,26.829745,30.467823,28.356196,29.468957,31.767153,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,55.134537,24.279127,26.245930,21.930849,26.729478,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,46.157655,19.126968,19.067417,15.811030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.940765,15.088979,16.552107
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.077220,10.225925,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.479337,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [57]:
ALLsnps = np.sum(np.sum(jSFS, axis=1))
ALLsnps

20724.000000000073

In [12]:
## input file for parameter estimates for ThujajAFS_d3_ForParamEst.obs
infile ="jAFS_d3_ParamEst.obs"

In [13]:
jSFSfile = open(infile, "r")
##get ride of first two lines
allLines = jSFSfile.readlines()
allLines = allLines[2:]

In [14]:
allLinesallLines

['d1_0\t3911.403782193901 1963.986436704424 816.7096727944424 290.6215166534836 198.8152269028916 110.1933427181623 100.5723525371179 54.14223161374683 44.62404728712639 34.37045728947071 24.88499041132458 19.93495369220623 20.39406975644497 14.86108939870568 52.29597605438708 3075.166872282226 400.0687342802146 257.6282728152913\n',
 'd1_1\t138.4882466945223 96.89073585282986 61.18920354668642 38.31804344561868 27.65415685770868 21.89334148554998 16.87924516999421 14.86652576112308 10.94921250027563 10.38094099412623 10.86553087550531 32.98255420898501 1647.359720083964 267.4438033825524 208.1264657649273 121.0118141020115 90.71080802116182 64.08748678977253\n',
 'd1_2\t42.73359441610419 30.95976216403006 26.17927749924907 22.10490981115597 20.05541458969739 14.15745105469575 14.06730479531977 11.07164875165162 0 802.244592775035 157.2837617868084 139.6799857362773 90.93765966573156 73.50937694262203 54.38396468843958 40.66537428575099 30.0343857436857 26.29743019709975\n',
 'd1_3\t24.76977783533697 18.3012606356946 12.63414933625813 11.71127735058471 0 0 623.6799765385344 114.3566320699233 110.0376154343226 80.61670198493368 72.39658670470141 53.47222567050816 45.19800487170521 37.24357646444503 28.98494516484228 23.3825746308478 20.35882967156035 14.45572483524828\n',
 'd1_4\t0 0 0 376.7300016146789 81.10299791771764 82.66257111582443 67.29961616425862 70.09000789096669 50.02962496440654 42.63089485651487 37.03193835339525 29.65926910920976 24.19385176291556 22.32514298741656 0 0 0 0\n',
 'd1_5\t267.5571149084099 65.73671699769412 66.27862096383065 58.96203145188608 64.77420958825881 48.97988009311032 45.17074515836789 40.52058767399606 34.69618042517527 27.79629772943907 0 0 0 0 0 184.162929132604 50.78200412414891 51.07543290251989\n',
 'd1_6\t47.258618835749 50.75504995325557 46.09106873783189 45.47547714665857 41.0530683907325 38.6285107631801 0 0 0 0 0 0 138.4880644260738 39.29455854699301 43.5387962984106 41.43270605040432 42.01192285240738 43.1887847700617\n',
 'd1_7\t43.19871962632258 41.4914158514643 0 0 0 0 0 0 0 104.1674582729018 31.63160469135006 37.72407841110818 35.67161595191991 34.37714392591149 36.71981799449392 40.11768126156633 0 0\n',
 'd1_8\t0 0 0 0 0 0 76.96035590897672 26.82974468461816 30.46782333289832 28.35619638905892 29.46895714509086 31.76715330271048 0 0 0 0 0 0\n',
 'd1_9\t0 0 0 55.1345369819763 24.27912652570369 26.2459295227893 21.93084894971757 26.72947786566584 0 0 0 0 0 0 0 0 0 0\n',
 'd1_10\t46.15765505472869 19.126967811364 19.06741706465463 15.8110299281701 0 0 0 0 0 0 0 0 0 0 0 44.94076511519805 15.08897889668524 16.55210742042323\n',
 'd1_11\t0 0 0 0 0 0 0 0 0 0 0 0 35.07721996963429 10.22592541411379 0 0 0 0\n',
 'd1_12\t0 0 0 0 0 0 0 0 0 52.47933704466647 0 0 0 0 0 0 0 0\n',
 'd1_13\t0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n',
 'd1_14\t0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n']

In [23]:
sumfile="jAFS_edited_forParam4plot.obs"
outFile = open(sumfile, "a")
for line in allLines:
    rows = line.split("\t")[1].strip()
    print(rows)
    sites = rows.split(" ")
    for singleSiteFreq in sites:
        print(singleSiteFreq+"\t")
        outFile.write(singleSiteFreq+"\t")

## add return for each SFS flattened
summaryOutputfile.write("\n")

3911.403782193901 1963.986436704424 816.7096727944424 290.6215166534836 198.8152269028916 110.1933427181623 100.5723525371179 54.14223161374683 44.62404728712639 34.37045728947071 24.88499041132458 19.93495369220623 20.39406975644497 14.86108939870568 52.29597605438708 3075.166872282226 400.0687342802146 257.6282728152913
3911.403782193901
1963.986436704424
816.7096727944424
290.6215166534836
198.8152269028916
110.1933427181623
100.5723525371179
54.14223161374683
44.62404728712639
34.37045728947071
24.88499041132458
19.93495369220623
20.39406975644497
14.86108939870568
52.29597605438708
3075.166872282226
400.0687342802146
257.6282728152913
138.4882466945223 96.89073585282986 61.18920354668642 38.31804344561868 27.65415685770868 21.89334148554998 16.87924516999421 14.86652576112308 10.94921250027563 10.38094099412623 10.86553087550531 32.98255420898501 1647.359720083964 267.4438033825524 208.1264657649273 121.0118141020115 90.71080802116182 64.08748678977253
138.4882466945223
96.89073585282986
61.18920354668642
38.31804344561868
27.65415685770868
21.89334148554998
16.87924516999421
14.86652576112308
10.94921250027563
10.38094099412623
10.86553087550531
32.98255420898501
1647.359720083964
267.4438033825524
208.1264657649273
121.0118141020115
90.71080802116182
64.08748678977253
42.73359441610419 30.95976216403006 26.17927749924907 22.10490981115597 20.05541458969739 14.15745105469575 14.06730479531977 11.07164875165162 0 802.244592775035 157.2837617868084 139.6799857362773 90.93765966573156 73.50937694262203 54.38396468843958 40.66537428575099 30.0343857436857 26.29743019709975
42.73359441610419
30.95976216403006
26.17927749924907
22.10490981115597
20.05541458969739
14.15745105469575
14.06730479531977
11.07164875165162
0
802.244592775035
157.2837617868084
139.6799857362773
90.93765966573156
73.50937694262203
54.38396468843958
40.66537428575099
30.0343857436857
26.29743019709975
24.76977783533697 18.3012606356946 12.63414933625813 11.71127735058471 0 0 623.6799765385344 114.3566320699233 110.0376154343226 80.61670198493368 72.39658670470141 53.47222567050816 45.19800487170521 37.24357646444503 28.98494516484228 23.3825746308478 20.35882967156035 14.45572483524828
24.76977783533697
18.3012606356946
12.63414933625813
11.71127735058471
0
0
623.6799765385344
114.3566320699233
110.0376154343226
80.61670198493368
72.39658670470141
53.47222567050816
45.19800487170521
37.24357646444503
28.98494516484228
23.3825746308478
20.35882967156035
14.45572483524828
0 0 0 376.7300016146789 81.10299791771764 82.66257111582443 67.29961616425862 70.09000789096669 50.02962496440654 42.63089485651487 37.03193835339525 29.65926910920976 24.19385176291556 22.32514298741656 0 0 0 0
0
0
0
376.7300016146789
81.10299791771764
82.66257111582443
67.29961616425862
70.09000789096669
50.02962496440654
42.63089485651487
37.03193835339525
29.65926910920976
24.19385176291556
22.32514298741656
0
0
0
0
267.5571149084099 65.73671699769412 66.27862096383065 58.96203145188608 64.77420958825881 48.97988009311032 45.17074515836789 40.52058767399606 34.69618042517527 27.79629772943907 0 0 0 0 0 184.162929132604 50.78200412414891 51.07543290251989
267.5571149084099
65.73671699769412
66.27862096383065
58.96203145188608
64.77420958825881
48.97988009311032
45.17074515836789
40.52058767399606
34.69618042517527
27.79629772943907
0
0
0
0
0
184.162929132604
50.78200412414891
51.07543290251989
47.258618835749 50.75504995325557 46.09106873783189 45.47547714665857 41.0530683907325 38.6285107631801 0 0 0 0 0 0 138.4880644260738 39.29455854699301 43.5387962984106 41.43270605040432 42.01192285240738 43.1887847700617
47.258618835749
50.75504995325557
46.09106873783189
45.47547714665857
41.0530683907325
38.6285107631801
0
0
0
0
0
0
138.4880644260738
39.29455854699301
43.5387962984106
41.43270605040432
42.01192285240738
43.1887847700617
43.19871962632258 41.4914158514643 0 0 0 0 0 0 0 104.1674582729018 31.63160469135006 37.72407841110818 35.67161595191991 34.37714392591149 36.71981799449392 40.11768126156633 0 0
43.19871962632258
41.4914158514643
0
0
0
0
0
0
0
104.1674582729018
31.63160469135006
37.72407841110818
35.67161595191991
34.37714392591149
36.71981799449392
40.11768126156633
0
0
0 0 0 0 0 0 76.96035590897672 26.82974468461816 30.46782333289832 28.35619638905892 29.46895714509086 31.76715330271048 0 0 0 0 0 0
0
0
0
0
0
0
76.96035590897672
26.82974468461816
30.46782333289832
28.35619638905892
29.46895714509086
31.76715330271048
0
0
0
0
0
0
0 0 0 55.1345369819763 24.27912652570369 26.2459295227893 21.93084894971757 26.72947786566584 0 0 0 0 0 0 0 0 0 0
0
0
0
55.1345369819763
24.27912652570369
26.2459295227893
21.93084894971757
26.72947786566584
0
0
0
0
0
0
0
0
0
0
46.15765505472869 19.126967811364 19.06741706465463 15.8110299281701 0 0 0 0 0 0 0 0 0 0 0 44.94076511519805 15.08897889668524 16.55210742042323
46.15765505472869
19.126967811364
19.06741706465463
15.8110299281701
0
0
0
0
0
0
0
0
0
0
0
44.94076511519805
15.08897889668524
16.55210742042323
0 0 0 0 0 0 0 0 0 0 0 0 35.07721996963429 10.22592541411379 0 0 0 0
0
0
0
0
0
0
0
0
0
0
0
0
35.07721996963429
10.22592541411379
0
0
0
0
0 0 0 0 0 0 0 0 0 52.47933704466647 0 0 0 0 0 0 0 0
0
0
0
0
0
0
0
0
0
52.47933704466647
0
0
0
0
0
0
0
0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

1

In [28]:
infile="jAFS_edited_forParam4plot.obs"
obs_sfs = pd.read_table(infile)
#obs_sfs

In [39]:
infile="jAFS_d3_ParamEst.obs"
obs_sfs = pd.read_table(infile)
obs_sfs

,Unnamed: 0,d0_0,d0_1,d0_2,d0_3,d0_4,d0_5,d0_6,d0_7,d0_8,d0_9,d0_10,d0_11,d0_12,d0_13,d0_14,d0_15,d0_16,d0_17
0,d1_0,3911.403782,1963.986437,816.709673,290.621517,198.815227,110.193343,100.572353,54.142232,44.624047,34.370457,24.884990,19.934954,20.394070,14.861089,52.295976,3075.166872,400.068734,257.628273
1,d1_1,138.488247,96.890736,61.189204,38.318043,27.654157,21.893341,16.879245,14.866526,10.949213,10.380941,10.865531,32.982554,1647.359720,267.443803,208.126466,121.011814,90.710808,64.087487
2,d1_2,42.733594,30.959762,26.179277,22.104910,20.055415,14.157451,14.067305,11.071649,0.000000,802.244593,157.283762,139.679986,90.937660,73.509377,54.383965,40.665374,30.034386,26.297430
3,d1_3,24.769778,18.301261,12.634149,11.711277,0.000000,0.000000,623.679977,114.356632,110.037615,80.616702,72.396587,53.472226,45.198005,37.243576,28.984945,23.382575,20.358830,14.455725
4,d1_4,0.000000,0.000000,0.000000,376.730002,81.102998,82.662571,67.299616,70.090008,50.029625,42.630895,37.031938,29.659269,24.193852,22.325143,0.000000,0.000000,0.000000,0.000000
5,d1_5,267.557115,65.736717,66.278621,58.962031,64.774210,48.979880,45.170745,40.520588,34.696180,27.796298,0.000000,0.000000,0.000000,0.000000,0.000000,184.162929,50.782004,51.075433
6,d1_6,47.258619,50.755050,46.091069,45.475477,41.053068,38.628511,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,138.488064,39.294559,43.538796,41.432706,42.011923,43.188785
7,d1_7,43.198720,41.491416,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,104.167458,31.631605,37.724078,35.671616,34.377144,36.719818,40.117681,0.000000,0.000000
8,d1_8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.960356,26.829745,30.467823,28.356196,29.468957,31.767153,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,d1_9,0.000000,0.000000,0.000000,55.134537,24.279127,26.245930,21.930849,26.729478,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,d1_10,46.157655,19.126968,19.067417,15.811030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.940765,15.088979,16.552107
11,d1_11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.077220,10.225925,0.000000,0.000000,0.000000,0.000000
12,d1_12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.479337,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,d1_13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,d1_14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000